1 Module
js-tasks-ru/jsbasic-20220113_nxashiev pull request #3
Opened 2022-01-18 16:58 UTC by Khashiev

2022-01-18 16:59 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-19 10:44 UTC, SinimaWath requested changes

2022-01-19 10:44 UTC, SinimaWath commented on 1-module/4-task/index.js
> +  return false;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return str2.includes("1xbet") || str2.includes("xxx")`

Это как раз тот случай

2022-01-19 10:44 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  return true;
Обычно малое количество правил(меньше 4), можно лаконично уместить в return:
`return !name....`

Это как раз тот случай

2022-01-19 10:44 UTC, SinimaWath commented on 1-module/3-task/index.js
> +  if (str == "") {
Это можно заменить на: `if (!str)` - и тем самым, мы еще защищаемся от null, undefined

2022-01-19 12:03 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-01-19 20:32 UTC, SinimaWath approved these changes

2022-01-19 20:33 UTC, merged